// Generated by gencpp from file plant_arm_project/PlantLocation.msg
// DO NOT EDIT!


#ifndef PLANT_ARM_PROJECT_MESSAGE_PLANTLOCATION_H
#define PLANT_ARM_PROJECT_MESSAGE_PLANTLOCATION_H

#include <ros/service_traits.h>


#include <plant_arm_project/PlantLocationRequest.h>
#include <plant_arm_project/PlantLocationResponse.h>


namespace plant_arm_project
{

struct PlantLocation
{

typedef PlantLocationRequest Request;
typedef PlantLocationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlantLocation
} // namespace plant_arm_project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::plant_arm_project::PlantLocation > {
  static const char* value()
  {
    return "16118a8f43cad3bb5033f2cceac3aadb";
  }

  static const char* value(const ::plant_arm_project::PlantLocation&) { return value(); }
};

template<>
struct DataType< ::plant_arm_project::PlantLocation > {
  static const char* value()
  {
    return "plant_arm_project/PlantLocation";
  }

  static const char* value(const ::plant_arm_project::PlantLocation&) { return value(); }
};


// service_traits::MD5Sum< ::plant_arm_project::PlantLocationRequest> should match
// service_traits::MD5Sum< ::plant_arm_project::PlantLocation >
template<>
struct MD5Sum< ::plant_arm_project::PlantLocationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::plant_arm_project::PlantLocation >::value();
  }
  static const char* value(const ::plant_arm_project::PlantLocationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::plant_arm_project::PlantLocationRequest> should match
// service_traits::DataType< ::plant_arm_project::PlantLocation >
template<>
struct DataType< ::plant_arm_project::PlantLocationRequest>
{
  static const char* value()
  {
    return DataType< ::plant_arm_project::PlantLocation >::value();
  }
  static const char* value(const ::plant_arm_project::PlantLocationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::plant_arm_project::PlantLocationResponse> should match
// service_traits::MD5Sum< ::plant_arm_project::PlantLocation >
template<>
struct MD5Sum< ::plant_arm_project::PlantLocationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::plant_arm_project::PlantLocation >::value();
  }
  static const char* value(const ::plant_arm_project::PlantLocationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::plant_arm_project::PlantLocationResponse> should match
// service_traits::DataType< ::plant_arm_project::PlantLocation >
template<>
struct DataType< ::plant_arm_project::PlantLocationResponse>
{
  static const char* value()
  {
    return DataType< ::plant_arm_project::PlantLocation >::value();
  }
  static const char* value(const ::plant_arm_project::PlantLocationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLANT_ARM_PROJECT_MESSAGE_PLANTLOCATION_H
