// Generated by gencpp from file plant_arm_project/PlantLocationResponse.msg
// DO NOT EDIT!


#ifndef PLANT_ARM_PROJECT_MESSAGE_PLANTLOCATIONRESPONSE_H
#define PLANT_ARM_PROJECT_MESSAGE_PLANTLOCATIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace plant_arm_project
{
template <class ContainerAllocator>
struct PlantLocationResponse_
{
  typedef PlantLocationResponse_<ContainerAllocator> Type;

  PlantLocationResponse_()
    : sucess(0)  {
    }
  PlantLocationResponse_(const ContainerAllocator& _alloc)
    : sucess(0)  {
  (void)_alloc;
    }



   typedef int64_t _sucess_type;
  _sucess_type sucess;





  typedef boost::shared_ptr< ::plant_arm_project::PlantLocationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::plant_arm_project::PlantLocationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PlantLocationResponse_

typedef ::plant_arm_project::PlantLocationResponse_<std::allocator<void> > PlantLocationResponse;

typedef boost::shared_ptr< ::plant_arm_project::PlantLocationResponse > PlantLocationResponsePtr;
typedef boost::shared_ptr< ::plant_arm_project::PlantLocationResponse const> PlantLocationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::plant_arm_project::PlantLocationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::plant_arm_project::PlantLocationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::plant_arm_project::PlantLocationResponse_<ContainerAllocator1> & lhs, const ::plant_arm_project::PlantLocationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sucess == rhs.sucess;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::plant_arm_project::PlantLocationResponse_<ContainerAllocator1> & lhs, const ::plant_arm_project::PlantLocationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace plant_arm_project

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::plant_arm_project::PlantLocationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plant_arm_project::PlantLocationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plant_arm_project::PlantLocationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plant_arm_project::PlantLocationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plant_arm_project::PlantLocationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plant_arm_project::PlantLocationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::plant_arm_project::PlantLocationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4e3fb0f8e6a0a6dee863e25b851d1aa7";
  }

  static const char* value(const ::plant_arm_project::PlantLocationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4e3fb0f8e6a0a6deULL;
  static const uint64_t static_value2 = 0xe863e25b851d1aa7ULL;
};

template<class ContainerAllocator>
struct DataType< ::plant_arm_project::PlantLocationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "plant_arm_project/PlantLocationResponse";
  }

  static const char* value(const ::plant_arm_project::PlantLocationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::plant_arm_project::PlantLocationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 sucess\n"
;
  }

  static const char* value(const ::plant_arm_project::PlantLocationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::plant_arm_project::PlantLocationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sucess);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlantLocationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::plant_arm_project::PlantLocationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::plant_arm_project::PlantLocationResponse_<ContainerAllocator>& v)
  {
    s << indent << "sucess: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sucess);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANT_ARM_PROJECT_MESSAGE_PLANTLOCATIONRESPONSE_H
